### ISSUE TITLE
Conda forge

### ISSUE THREAD

**Issue by Acribbs** [gridengine/drmaa2-python#2]
Just wondering if there are plans to release this as a Conda-forge feedstock? Would like to integrate this into our tools but it would need to be distributed as a Conda package. Would be happy to help.

**Comment by alea55** [comment]
This is currently not on our roadmap but packets are regularly made available on pypi. If you are eager to contribute the necessary packaging recipes please feel welcome...

**Comment by Acribbs** [comment]
Great, I will go ahead and package this when I have time as I won't be able to use it otherwise. Thanks. I will keep you updated on progress

**Comment by Acribbs** [comment]
Hi, just working on Conda package and have a question, why is the pypi release named ugh-drmaa2? Is there a specific reasoning and would you like the Conda package to be called the same or drmaa2?

**Comment by Acribbs** [comment]
It seems reasonable that I go with the pypi name but happy to be advised otherwise.

**Comment by alea55** [comment]
It is called uge-drmaa2 since drmaa2 is a more open standard in general but the implementation of the drmaa2-python module is build and tested with Univa Grid Engine. Therefore the acronym uge-drmaa2. I would recommend to use the same naming scheme as we do for pypi, then the versioning will be following the same rationale. But there may be some conventions for conda that I don't know of. If this should be the case then go ahead and adjust accordingly. It should follow some clear scheme to be able to identify any version specific changes.
We are kind of mimicking the version scheme of UGE with some additions that are required by pypi package management e.g. 8.6.12a0  equals first alpha of 8.6.12. b for beta and p0, p1 for any version specific package patch.

**Comment by Acribbs** [comment]
Perfect. thanks

**Comment by Acribbs** [comment]
Have created a recipe (https://github.com/conda-forge/staged-recipes/pull/11496) so will close this now. Thanks.
